name: Build School App APK
on:
  push:
    branches: [ main ] # Jab aap main branch me code dalenge

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Expo CLI & EAS
        run: npm install -g expo-cli eas-cli

      - name: Install Dependencies
        run: npm install

      - name: Build APK (EAS)
        run: eas build --platform android --profile preview --non-interactive
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }} # Aapka Expo Secret Key
